export const LOAD_CONVERSATION_LIST = 'LOAD_CONVERSATION_LIST';
export const CONVERSATION_LIST_FAIL = 'CONVERSATION_LIST_FAIL';


export const LOAD_CONVERSATION_DETAIL = 'LOAD_CONVERSATION_DETAIL';
export const CONVERSATION_DETAIL_FAIL = 'CONVERSATION_DETAIL_FAIL';



export const LOAD_CONVERSATION_CHATS = 'LOAD_CONVERSATION_CHATS';
export const CONVERSATION_CHATS_FAIL = 'CONVERSATION_CHATS_FAIL';
export const CREATE_CONVERSATION = 'CREATE_CONVERSATION';



export const CREATE_CHAT = 'CREATE_CHAT';


